/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication21;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jpl7.Query;

/**
 *
 * @author Basem Elsayed
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public String w1, w2, w3, w4, w5, w6, w7, w8;
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        word1 = new javax.swing.JTextField();
        word2 = new javax.swing.JTextField();
        word3 = new javax.swing.JTextField();
        word4 = new javax.swing.JTextField();
        word5 = new javax.swing.JTextField();
        word6 = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        word7 = new javax.swing.JTextField();
        word8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        word1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                word1ActionPerformed(evt);
            }
        });

        word2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                word2ActionPerformed(evt);
            }
        });

        word3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                word3ActionPerformed(evt);
            }
        });

        word4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                word4ActionPerformed(evt);
            }
        });

        word5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                word5ActionPerformed(evt);
            }
        });

        word6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                word6ActionPerformed(evt);
            }
        });

        sendButton.setText("Send Words");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        word7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                word7ActionPerformed(evt);
            }
        });

        word8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                word8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(word1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(word2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(word3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(word4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(word5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(word6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(word7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(word8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(word1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(word3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(word5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(word7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(word8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void word3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_word3ActionPerformed
        
    }//GEN-LAST:event_word3ActionPerformed

    private void word1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_word1ActionPerformed
        
    }//GEN-LAST:event_word1ActionPerformed

    private void word2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_word2ActionPerformed
       
    }//GEN-LAST:event_word2ActionPerformed

    private void word4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_word4ActionPerformed
        
    }//GEN-LAST:event_word4ActionPerformed

    private void word5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_word5ActionPerformed
        
    }//GEN-LAST:event_word5ActionPerformed

    private void word6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_word6ActionPerformed
        
    }//GEN-LAST:event_word6ActionPerformed

    private void word7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_word7ActionPerformed

    }//GEN-LAST:event_word7ActionPerformed

    private void word8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_word8ActionPerformed
        
    }//GEN-LAST:event_word8ActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        
        w1 = word1.getText();
        w2 = word2.getText();
        w3 = word3.getText();
        w4 = word4.getText();
        w5 = word5.getText();
        w6 = word6.getText();
        w7 = word7.getText();
        w8 = word8.getText();
        
        w1 += ".";
        w2 += ".";
        w3 += ".";
        w4 += ".";
        w5 += ".";
        w6 += ".";
        w7 += ".";
        w8 += ".";
        
        try {
            
            /*
            
                zombifies
                akecabele
                brickwork
                backcheck
                acmrremad
                nhgwpfabz
                jellybean
                earreoded
            
            */
            
            File inputFile = new File("C:\\Users\\Ahmed\\Desktop\\20150071\\input.txt");
            PrintWriter  writer = new PrintWriter(inputFile);
            writer.write(w1);
            writer.write("\n");
            writer.write(w2);
            writer.write("\n");
            writer.write(w3);
            writer.write("\n");
            writer.write(w4);
            writer.write("\n");
            writer.write(w5);
            writer.write("\n");
            writer.write(w6);
            writer.write("\n");
            writer.write(w7);
            writer.write("\n");
            writer.write(w8);
            writer.close();
            String s = "consult('C:/Users/Ahmed/Desktop/20150071/20150071.pl')";
            Query q1 = new Query(s);
            System.out.println("consult " + (q1.hasSolution() ? "succeeded" : "failed"));
             
            q1 = new Query("test");
            System.out.println("consult " + (q1.hasSolution() ? "succeeded" : "failed"));
            text.setText(print());
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_sendButtonActionPerformed

    
    
    
    
    
    public String print()
    {
        try {
            
            String allContents = new Scanner(new File("C:\\Users\\Ahmed\\Desktop\\20150071\\output.txt")).useDelimiter("\\Z").next();
            if(allContents.charAt(0) == '0')
            {
                return "A Solution Not Found!!";
            }
            
            System.out.println(allContents);
            String []mainSplit = allContents.split("#");
            String []verticles = mainSplit[0].split("\\$");
            
            
            String out = "         " + "V1      " + "V2      " + "V3      " + "V4\n";
            out += "        ";
            for(int i=0; i<verticles[0].length() ;i++)
            {
                if(i == 0)
                    out += "      " + verticles[0].charAt(i);
                else if(i == 1)
                    out += "       " + verticles[0].charAt(i);
                else
                    out += "       " + verticles[0].charAt(i);

            }
            out += "\n";
            out += "H1";
            for(int i=1; i<mainSplit[1].length()-1 ;i+=2)
            {
                out += "   " + mainSplit[1].charAt(i);
            }
            out += "\n";
            
            ////////////////////////////////////////////////
            out += "        ";
            for(int i=0; i<verticles[1].length() ;i++)
            {
                if(i == 0)
                    out += "      " + verticles[1].charAt(i);
                else if(i == 1)
                    out += "       " + verticles[1].charAt(i);
                else
                    out += "       " + verticles[1].charAt(i);

            }
            out += "\n";
            out += "H2";
            for(int i=1; i<mainSplit[2].length()-1 ;i+=2)
            {
                out += "   " + mainSplit[2].charAt(i);
            }
            out += "\n";
            ///////////////////////////////////////////////
            
            out += "       ";
            for(int i=0; i<verticles[2].length() ;i++)
            {
                if(i == 0)
                    out += "      " + verticles[2].charAt(i);
                else if(i == 1)
                    out += "       " + verticles[2].charAt(i);
                else
                    out += "       " + verticles[2].charAt(i);

            }
            out += "\n";
            out += "H3";
            for(int i=1; i<mainSplit[3].length()-1 ;i+=2)
            {
                out += "   " + mainSplit[3].charAt(i);
            }
            out += "\n";
            ////////////////////////////////////////////////
            
            out += "       ";
            for(int i=0; i<verticles[3].length() ;i++)
            {
                if(i == 0)
                    out += "      " + verticles[3].charAt(i);
                else if(i == 1)
                    out += "       " + verticles[3].charAt(i);
                else
                    out += "       " + verticles[3].charAt(i);

            }
            out += "\n";
            out += "H4";
            for(int i=1; i<mainSplit[4].length()-1 ;i+=2)
            {
                out += "   " + mainSplit[4].charAt(i);
            }
            out += "\n";
            
            //////////////////////////////////////////////////////
            
            out += "       ";
            for(int i=0; i<verticles[4].length() ;i++)
            {
                if(i == 0)
                    out += "      " + verticles[4].charAt(i);
                else if(i == 1)
                    out += "       " + verticles[4].charAt(i);
                else
                    out += "       " + verticles[4].charAt(i);

            }
            
            return out;

        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "A Solution Not Found!!";
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea text;
    private javax.swing.JTextField word1;
    private javax.swing.JTextField word2;
    private javax.swing.JTextField word3;
    private javax.swing.JTextField word4;
    private javax.swing.JTextField word5;
    private javax.swing.JTextField word6;
    private javax.swing.JTextField word7;
    private javax.swing.JTextField word8;
    // End of variables declaration//GEN-END:variables
}
